services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=main_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"