ktor:
    application:
        modules:
            - com.bussab_guilherme.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: postgres
  password: password