ktor:
    application:
        modules:
            - com.bussab_guilherme.ApplicationKt.module
    deployment:
        port: 8080
        secureCookie: false
postgres:
  url: "jdbc:postgresql://localhost:5432/main_db"
  user: postgres
  password: password